---

- name: Create a pxe server
  hosts: all
  become: true
  gather_facts: false

  tasks:


    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - dnsmasq
        - syslinux 
        - tftp-server
        - vsftpd

    - name: Create dnsmasq template
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf

    - name: Copy syslinux files
      shell: cp -r /usr/share/syslinux/* /var/lib/tftpboot

    - name: Create pxe server config file
      file:
        path: /var/lib/tftpboot/pxelinux.cfg
        state: directory

    - name: Create pxe server images dir
      file:
        path: /var/lib/tftpboot/images
        state: directory

    - name: Create pxe default template
      template:
        src: default.j2
        dest: /var/lib/tftpboot/pxelinux.cfg/default
      tags: template  

    - name: Create centos7 kickstart
      template:
        src: centos7.ks.j2
        dest: /var/ftp/pub/centos7/centos7.ks
      tags: template  

    - name: Restart tftp
      systemd:
        name: tftp
        state: restarted
      tags: template  

    - name: Restart vsftpd
      systemd:
        name: vsftpd
        state: restarted
      tags: template  

    - name: Start and enable the services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
        daemon_reload: yes
      with_items:
        - dnsmasq
        - vsftpd
      tags:
        start

    # TODO: could improve upon this...
    - name: Disable firewall
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
        daemon_reload: yes
      with_items:
        - firewalld
      tags:
        firewall
